(again) added support for SD card detection
xiphonics/picoTracker pull request #159
Opened 2024-03-12 15:26 UTC by Speccery

Thanks @maks for your comments. Please take a look if this PR makes more sense - I followed your advice and applied a patch to the head of the master branch. This was what I was trying to the last time around, but in the meantime there had been quite a few commits to master and I was also trying out things... Below the NO_EXIT definition tests coming back is a bit surprising, I will take a look.

Simple modifications to detect if an SD card is not in the picoTracker (based on existing code for SD card presence and filesystem mount). Between making my edits the master branch had a bunch of changes, among them there seems to be a change on the policy of how '#ifdef PICOSYSTEM' is used.

2024-03-12 16:02 UTC, democloid requested changes
This adds a lot of logic that I don't think is necessary. First thing we do when we open the select project dialog is to open the root of the card. If the root cannot be read, then we can probably infer that there is a problem with the card. It's just an "else" for the "if" in line 255 (in master)

2024-03-13 20:30 UTC, Speccery commented on sources/CMakeLists.txt
> +add_compile_options($<$<COMPILE_LANGUAGE:CXX>:-Wno-c++20-compat>)
These are probably specific to my build environment tool versions (macos homebrew gcc-arm-embedded) and should not be included. There was a type conflict with char8_t c++20 and another warning about virtual functions. I am traveling and replying with my smartphone so can't check the exact message at the moment.

2024-03-13 20:33 UTC, Speccery commented on sources/Application/Views/ModalDialogs/SelectProjectDialog.cpp
> +    content_.Insert(new Path(msg));
Thanks and agreed - Yes a messagebox would make more sense. I'm not familiar yet with all the UI elements which are available in the codebase.

2024-03-13 23:13 UTC, maks commented on sources/Application/Views/ModalDialogs/SelectProjectDialog.cpp
> +    content_.Insert(new Path(msg));
Thanks @Speccery for working on this!  With Messagebox there is an example of using it in [ProjectView](https://github.com/democloid/picoTracker/blob/17a7206f1a854c298989545d713f3bd2d8b2a86a/sources/Application/Views/ProjectView.cpp#L197) which might be of help

2024-12-02 05:35 UTC, maks commented
@Speccery  apologies for not getting back to this sooner, but with the large changes in the codebase for version 2.0, it was easier to just implement this from scratch in the boot process to start with in #250, so I'll close this PR off.

2024-12-02 05:35 UTC, closed without merging