Adding slices
xiphonics/picoTracker pull request #173
Opened 2024-04-03 09:50 UTC by djdiskmachine

Rebased on master
Issue when loading project "restoring allocation" whenever 164-170 are added

2024-04-03 11:55 UTC, democloid requested changes
Regarding the crash, have you tried to create a new project to test this?

2024-04-03 11:59 UTC, djdiskmachine commented on sources/Application/Instruments/SampleInstrument.h
> +#define SIP_SLICES MAKE_FOURCC('S','L','C','S')
Yes working on it!

2024-04-03 12:10 UTC, djdiskmachine commented on sources/Application/Views/InstrumentView.cpp
> +
Yes, It's added conditionally but it's not perfect
You have to exit then enter the instrument screen for it to refresh, I can't figure out how to make it refresh when selecting slicer
![PXL_20240403_120826428 MP~2](https://github.com/democloid/picoTracker/assets/110535302/c4063a21-4040-42fd-9552-bf53e2d5f2cb)
![PXL_20240403_120223122 MP~3](https://github.com/democloid/picoTracker/assets/110535302/1c49028f-59f6-4028-83dd-d704449ef8f7)

2024-04-06 13:25 UTC, democloid commented on docs/MANUAL.md
> +  - slicer will cut the sample into "slices" (displayed only in slice mode) amount of samples. Slices are mapped from C-2 (the lowest note) up to amount of slices. Example: slices == 4 will give you
@djdiskmachine Given that we have a "Root note" field, what do you think using that as the root of the slices? Or is it understood than any use of slices generally would start at C-2?

2024-04-11 07:38 UTC, djdiskmachine commented
@democloid rootnote will still affect the playback pitch. I made the implementation to be the same as on M8tracker, setting the first slice to C3 will make 48 the max number of slices. :)

2024-09-18 10:07 UTC, closed without merging

2024-09-18 14:17 UTC, djdiskmachine commented
@democloid is this still relevant or should i delete it?

2024-09-18 22:17 UTC, maks commented
@djdiskmachine please dont delete it! I'd really love to have slicing support in pT!
Sorry about this sitting untouched for so long! It will likely need a bit of rework onto the changes that are being done in the pT codebase, but I'm happy to put my hand up to help out with that.